# Generated by Django 5.2.7 on 2025-10-09 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoteCargaDatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(help_text='Ej: 2025A', max_length=10)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('reporte_caracterizacion', models.FileField(upload_to='uploads/')),
                ('reporte_notas', models.FileField(upload_to='uploads/')),
                ('reporte_pagos', models.FileField(upload_to='uploads/')),
                ('reporte_discapacidad', models.FileField(upload_to='uploads/')),
                ('procesado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='EstudiantePeriodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_estudiante', models.CharField(db_index=True, max_length=50)),
                ('periodo', models.CharField(db_index=True, max_length=10)),
                ('promedio_semestral', models.FloatField(blank=True, null=True)),
                ('num_materias_cursadas', models.IntegerField(blank=True, null=True)),
                ('num_materias_reprobadas', models.IntegerField(blank=True, null=True)),
                ('edad', models.IntegerField(blank=True, null=True)),
                ('genero', models.CharField(blank=True, max_length=50, null=True)),
                ('es_foraneo', models.IntegerField(blank=True, null=True)),
                ('pago_tardio', models.IntegerField(blank=True, null=True)),
                ('dias_retraso_pago', models.IntegerField(blank=True, null=True)),
                ('antiguedad_estudiante', models.IntegerField(blank=True, null=True)),
                ('discapacidad', models.CharField(blank=True, max_length=100, null=True)),
                ('ultima_prob_riesgo', models.FloatField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('id_estudiante', 'periodo')},
            },
        ),
    ]
