# Generated by Django 5.2.7 on 2025-10-09 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudianteperiodo',
            name='diferencia_promedio_anterior',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estudianteperiodo',
            name='estado_civil',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='estudianteperiodo',
            name='etnia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='estudianteperiodo',
            name='experiencia_laboral',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estudianteperiodo',
            name='num_est_economico',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estudianteperiodo',
            name='num_grupo_fam',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estudianteperiodo',
            name='periodo_ingreso',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='estudianteperiodo',
            name='posicion_hermanos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estudianteperiodo',
            name='programa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
