# Generated by Django 5.2.7 on 2025-10-09 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_estudianteperiodo_diferencia_promedio_anterior_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudianteperiodo',
            name='est_alum',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado del Alumno'),
        ),
    ]
